apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: argoproj/rollouts-demo:{{ .Values.version }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    blueGreen:
      # activeService는 승격시 새 템플리트 해시로 업데이트 할 서비스를 지정합니다.
      # 이 필드는 blueGreen 업데이트 전략에 필수입니다.
      activeService: {{ .Values.name }}-active
      # previewService는 승격 전에 새 템플리트 해시로 업데이트 할 서비스를 지정합니다.
      # 이를 통해 프로덕션 트래픽을 제공하지 않고 미리보기 스택에 도달 할 수 있습니다.
      # 이 필드는 선택 사항입니다.
      previewService: {{ .Values.name }}-preview
      # autoPromotionEnabled는 승격 직전에 롤아웃을 일시 중지하여 새 스택의 승격을 자동으로 비활성화합니다.
      # 이 옵션을 생략하면 기본 동작은 ReplicaSet가 완전히 준비/사용 가능한 즉시 새 스택을 승격시키는 것입니다.
      # 다음 명령어를 사용하여 롤아웃을 재개 할 수 있습니다.`kubectl argo rollouts resume ROLLOUT`
      autoPromotionEnabled: true
